### PR TITLE
Group liblove and lovedep projects in Visual Studio

### PR DESCRIPTION
**Pull request by learn-more**
This is the end result:

image

### CODE REVIEW

**Comment by slime73** [comment]
From the linux build failure:
```
CMake Error at extra/cmake/LoveMacros.cmake:11 (get_target_property):
  get_target_property() called with non-existent target "lua51".
Call Stack (most recent call first):
  CMakeLists.txt:1926 (love_group_projects)

-- Configuring incomplete, errors occurred!

CMake Error at extra/cmake/LoveMacros.cmake:13 (if):
  if given arguments:

    "STREQUAL" "INTERFACE_LIBRARY"

  Unknown arguments specified
```

**Comment by learn-more** [comment]
@slime73 This should now be fixed

**Comment by slime73** [comment]
This seems ok to me, but I'd like someone with more cmake experience to look at it as well.

**Comment by bartbes** [comment]
Would it make sense to also separate out the 3rd-party (love_3p) targets?

**Comment by learn-more** [comment]
> Would it make sense to also separate out the 3rd-party (love_3p) targets?

If you prefer that I can group those in a sub-folder as well.
Any suggestions for the name?
I'd think something like `lovedep/third-party` or so?

**Comment by slime73** [comment]
Maybe `liblove/libraries/` makes sense, given that they're in-source dependencies.

**Comment by learn-more** [comment]
image

**Comment by slime73** [comment]
Looks good, thanks!

**Pull request merged**
