### PR TITLE
Move all remaining instances of sprintf to snprintf.

### PR DESCRIPTION
**Pull request by devenvexe**
Remove all remaining calls to sprintf in favor of modern snprintf.

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
I'm not too positive of replacing every single sprintf to snprintf on 3rd-party libraries.

**Comment by slime73** [comment]
Yeah, I don't think we want to directly modify third party libraries like this. You could open issues in those libraries' respective upstream source code repositories (assuming they don't have newer versions which address this) - but it's possible they want to support older compilers too.

**Comment by devenvexe** [comment]
Ok, to confirm: third party code isn't modified in the course of Löve development? Alternatively: how do devs approach third party vs. first party code in this project?

**Comment by slime73** [comment]
> third party code isn't modified in the course of Löve development?

That's generally correct, except when there's something preventing the library from working with love. Sometimes we maintain a fork of a library if we have a change that won't be upstreamed in the near future (for example some [PhysFS changes](https://github.com/icculus/physfs/compare/main...slime73:physfs:mountRW) were necessary for a couple 12.0 features. I made an issue report in the PhysFS repository to go along with those changes.)

**Comment by devenvexe** [comment]
I got it. I'll close this PR. Thanks for the clarification.

**Pull request closed without merging**
