### PR TITLE
Support for Audio Device Selection and Disconnection Callback

### LINKED ISSUE #1537: Selecting audio output
**[Original report](https://bitbucket.org/rude/love/issue/1532) by Snusmumriken (Bitbucket: [MainTomato](https://bitbucket.org/MainTomato), GitHub: [MainTomato](https://github.com/MainTomato)).**

----------------------------------------

Love at starting selects the default audio output device and it cannot be changed. It can also lead to errors when connecting USB headphones with their own sound card: when default audio device is speakers, and you connect USB-headphones, the sound continues to flow through the speakers. And when headphones is default and you turn them off, the sound stops working. This feature may solve this weird behavior.

### PR DESCRIPTION
**Pull request by MikuAuahDark**
A simpler approach to #1804. Fixes #1537 _completely_.

This pull request adds several features:
* `love.audio.getPlaybackDevice()` function get current playback device name.
* `love.audio.getPlaybackDevices()` function retrieves all available playback devices in a Lua table.
* `love.audio.setPlaybackDevice(name)` function re-set the output device to `name`. `name` can be `nil` (for automatic default) or a string returned from `love.audio.getPlaybackDevices()` function above. Returns `true` on success or `false` and error message on failure.
* `love.audiodisconnected` callback when the audio device is disconnected and must be reconnected with `love.audio.setPlaybackDevice()`.

Now here are some notes:
* `love.audio.setPlaybackDevice()` is only supported if [ALC_SOFT_reopen_device](https://openal-soft.org/openal-extensions/SOFT_reopen_device.txt) extension is supported. Since you can't set to alternative device without this function, `love.audio.getPlaybackDevices()` is not really useful in that case. It could be possible to allow complete audio reinitialization with `love.audio.setPlaybackDevice()` before any other calls to `love.audio` is made to support scenario where "ALC_SOFT_reopen_device" extension is not supported but this adds slight complexity to the `Audio` class.
* `love.audiodisconnected` callback support depends on [ALC_EXT_disconnect](http://icculus.org/alextreg/wiki/action=printer&id=ALC_EXT_Disconnect) extension and is backend-dependent. It may or may not fire the callback when the audio is disconnected.
* When `love.audiodisconnected` callback is called, all previously playing sources are paused, then stopped a second later (`Source:tell()` returns 0). The latter may OpenAL-soft specific behavior though.
* Re-setting output device clears all the OpenAL internal buffer. ~~For "stream" sources, this desynchronize `Source:tell()` between the actual played audio, either slightly or significantly. For "static" sources, the source is stopped completely and must be re-played from the beginning.~~ I decided to stop all sources instead.

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
There are something that I want to implement. It's possible to retrieve all the source position before calling `Source::stop(pool)`.
* Should this be implemented and all the position of the sources are passed to `love.audiodisconnected` callback?
* If so, what would be the units? Seconds or samples?

**Comment by slime73** [comment]
> There are something that I want to implement. It's possible to retrieve all the source position before calling Source::stop(pool).
> Should this be implemented and all the position of the sources are passed to love.audiodisconnected callback?

Would it be possible to automatically seek the sources to their last playback position after stopping them (and before passing them to the callback)? Or would that need OpenAL state that isn't working by that point?

I also wonder if there needs to be any special consideration for queueable sources when doing that (e.g. not seeking those).

**Comment by MikuAuahDark** [comment]
Not possible. The audio state is disconnected during the `love.audiodisconnected` callback, so no `:play` or `:seek` should be called unless `love.audio.setPlaybackDevice` is called (and the user must return `true` so the callback didn't reconnect twice). The `love.audiodisconnected` callback reconnects the device to default device if user returns false or nil. I think this could be changed to check for string so that it reconnects to specific device.

**Comment by slime73** [comment]
> Not possible. The audio state is disconnected during the love.audiodisconnected callback

The tell and seek implementations have conditional codepaths depending on whether there's a valid OpenAL source associated with that love Source, though. So as long as they know that there's no valid OpenAL source after the disconnect, tell/seek should work, right?

**Comment by MikuAuahDark** [comment]
I tested it real quick and while it works for stream sources, it doesn't work for static sources at all. `alGetSourcei(source, AL_SAMPLE_OFFSET, &offset)` in `Source::tell` returns 0 in the `offset`.

**Comment by slime73** [comment]
Ok, let's put this in now and we can figure out possible streamlining and/or name changes later

**Pull request merged**
