### PR TITLE
Box2d update to 2.4.1

### PR DESCRIPTION
**Pull request by thegrb93**
Will probably work some more tomorrow on it

### CODE REVIEW

**Comment by thegrb93** [comment]
I heard there was some modifications to box2d originally for love2d, so those will need to be added in this as well.

**Comment by slime73** [comment]
I think this should be based on the 12.0-development branch rather than master, since master right now is mostly for fixes and small additions to 11.x.

**Comment by slime73** [comment]
> I heard there was some modifications to box2d originally for love2d, so those will need to be added in this as well.

From what I remember, we just have one modification - changing b2Assert in `Common/b2Settings.h` to throw a love C++ exception (via a new `loveAssert` function defined in b2Settings.cpp), rather than calling C's assert().

**Comment by thegrb93** [comment]
Ok, that shouldn't be difficult. Another task is to implement one-sided edge vs two-sided edge, and also ChainShape and EdgeShape's ghost vertices are no longer optional.

**Comment by thegrb93** [comment]
I should also rename the wrapper functions to their new box2d names. Also looks like Linux is failing to compile due to folder name casing.

**Comment by thegrb93** [comment]
Does anyone know whats going on here? It looks like a bug
https://github.com/love2d/love/blob/master/src/modules/physics/box2d/Physics.cpp#L210-L213

**Comment by thegrb93** [comment]
Nvm, it just decrements the reference counter

**Comment by thegrb93** [comment]
Looks like the CI is having a problem with the infinite function. For some reason its using cmath instead of math.h.

**Comment by thegrb93** [comment]
It compiles now but its having some kind of problem linking to liblove.so. I'll go ahead and ready for review.

**Comment by thegrb93** [comment]
Can't figure out how to get the linux build working. Someone said the autoconf is what does it, but I wasn't about to find any config scripts using the wrong box2d paths.

**Comment by thegrb93** [comment]
Do you know? @slime73

**Comment by slime73** [comment]
> Can't figure out how to get the linux build working. Someone said the autoconf is what does it, but I wasn't about to find any config scripts using the wrong box2d paths.

Sorry for taking so long to reply. I'm not too familiar with the Linux build setup but my guess is it has to do with the case change from Box2D to box2d - I see the `genmodules` script iterates over folders in the src/libraries and uses the folder names, and `configure.ac` references `enable_library_Box2D`. Maybe it should be changed to `enable_library_box2d`?

**Comment by thegrb93** [comment]
Thanks. I'll try that. Also I'm going to wait a bit because there's some more good updates on the way to box2d.

**Comment by thegrb93** [comment]
@slime73 Looks like that didn't work. I'd have to install linux and debug through it myself rather than using the CI to figure out what's wrong.

**Comment by slime73** [comment]
The build failure is different this time, at least - before that commit it was failing during linking because box2d symbols couldn't be found (presumably because the box2d library wasn't being built), now it's failing while compiling b2_island.cpp with an error about `dynamics/b2_contact_solver.h` not being found via #include.

**Comment by slime73** [comment]
I think this is another casing issue - in the erincatto/box2d repository, the subfolders in `src` are all lower case (`collision'`, `common`, `dynamics`, `rope`), whereas they're all capitalized (`Collision`, `Common`, `Dynamics`, `Rope`) in both the older version of box2d that's currently in love's repo, and the new one in your PR.

**Comment by thegrb93** [comment]
Oh good catch. Bad assumption on my part.

**Comment by thegrb93** [comment]
Yey Linux is working now. I imagine osx will need to be updated too (that I most definitely can't do). I think this should wait until https://github.com/erincatto/box2d/issues/645 is fixed and then I'll update box2d again.

**Comment by slime73** [comment]
> Yey Linux is working now. I imagine osx will need to be updated too (that I most definitely can't do). I think this should wait until erincatto/box2d#645 is fixed and then I'll update box2d again.

Sounds good. Don't worry about macOS, I'll update the Xcode project file once this goes in.

**Comment by thegrb93** [comment]
Looks like I can update again now. Will start that.

**Comment by thegrb93** [comment]
Will update to https://github.com/erincatto/box2d/releases/tag/v2.4.1

**Comment by thegrb93** [comment]
Need to add missing
```cpp
void loveAssert(bool test, const char *teststr)	
{	
	if (!test)	
		throw love::Exception("Box2D assertion failed: %s", teststr);	
}
```

**Comment by slime73** [comment]
Thanks for doing all the work to get the update working!

**Comment by thegrb93** [comment]
No problem, hopefully everything still works smoothly.

**Pull request merged**
