### PR TITLE
Add New macOS and iOS Icons to Better Comply with Current Apple HIG

### PR DESCRIPTION
**Pull request by CurbaiCode**
The current Apple platform icons have not been changed since 2016 (57697b3). Since then, with the release of macOS Big Sur, the Apple Human Interface Guidelines have changed. I created new icons for macOS and iOS that better match the look and feel of current Apple operating systems.

| iOS | macOS | GameIcon |
| --- | ----- | -------- |
| iOS icon | macOS icon | GameIcon icon |

### CODE REVIEW

**Comment by slime73** [comment]
This is a subjective thing but personally I like the colours and shading of the current icons better - I know on macOS icons are generally squircles instead of circular now, is there anything else in Apple's HIG that's changed?

**Comment by CurbaiCode** [comment]
Well, now they recommend "creating a design that works well on multiple platforms so that it feels at home on each", and right now the love macOS and iOS app icons don't quite match.

Even though the heart is not a real object, for macOS, Apple recommends that "if you depict real objects in your app icon, make them look like they’re made of physical materials and have actual mass." That's why I used the App Store, FaceTime, and Messages icons as a starting point for the app icons this PR adds.

And yes you are right, they recommend to "avoid defining contours that suggest a shape other than a rounded rectangle [a.k.a. squircle]."

For iOS, app icons are generally flatter looking, so I just flattened the macOS version to make the iOS version.

---
Sources:
[Current Apple app icon HIG](https://developer.apple.com/design/human-interface-guidelines/app-icons/)
[Archived version from 2018](https://web.archive.org/web/20180618155438/https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

**Comment by slime73** [comment]
The heart is similar to the music note on the iTunes icon I think - it's not an anatomical heart (physical object), it's a symbol.

**Comment by Labrium** [comment]
I agree that using these new macOS and iOS icons would not just align with Apple's new UI style, but as @CurbaiCode mentioned, it would also establish consistency with the other platforms Löve supports, as well as the wiki, homepage, and forums:

|Web Favicon|Windows (https://github.com/love2d/love/commit/9fae370c520f96b2815edc24c2f3f4c0af7a6cb2)|Linux (https://github.com/love2d/love/commit/60278b0532036d404c0b7b011c7b63ab58a5ddaf)|Android|iOS (New)|macOS (New)|
|-|-|-|-|-|-|
|Favicon|Windows icon|Linux icon|Android icon|iOS icon|macOS icon

**Comment by slime73** [comment]
> I know it is a symbol of a heart, but I like the depth and realism of having it look glassy like the camera on the FaceTime icon, rather than making it embossed like the Music icon.

Apple lets you locally change the icon of apps to your personal taste, if you want. But when you're looking to contribute to an app that you don't maintain in order to change the icon for everybody who uses that app, your own personal tastes are only a small part of the bigger picture. You'd need to be collaborative and flexible in order to be a successful contributor.

Starting with non-subjective things (such as the squircle HIG) is good, but for personal preferences there are better places to discuss that (such as the discord server) before trying to make a change for everyone here.

**Comment by Labrium** [comment]
> Apple lets you locally change the icon of apps to your personal taste

As a long-time Löve user myself, I have found it frustrating that changing the icon locally on macOS causes the app's drag-and-drop launch functionality to stop working. This probably isn't the place to go into the details, but I wanted to see if a release from your build system instead of my machine would still cause the same issue.

**Comment by CurbaiCode** [comment]
> Apple lets you locally change the icon of apps to your personal taste, if you want. But when you're looking to contribute to an app that you don't maintain in order to change the icon for everybody who uses that app, your own personal tastes are only a small part of the bigger picture. You'd need to be collaborative and flexible in order to be a successful contributor.
> 
> Starting with non-subjective things (such as the squircle HIG) is good, but for personal preferences there are better places to discuss them (such as the discord server) before trying to make a change for everyone here.

Thank you for reminding me. I guess I should have opened an issue or discussed it on discord first. I am flexible as to how the icon would look (like replacing the radial gradient for a two color split etc.), this is just what I had made. Sorry if I seemed imposing. Having been using love and loving it (no pun intended), I just wanted to help keep it up to date.

**Comment by slime73** [comment]
From an unrelated discussion in the Discord server, we may want to move away from the specific colours of the windows / etc. icons (maybe toward something more pastel, but nothing's been decided yet). So for now I'd rather not update the Mac and iOS icons to colours that we're likely going to change again in the future.

**Pull request closed without merging**
