### PR TITLE
Add lua files to CMakeLists.txt

### PR DESCRIPTION
**Pull request by learn-more**
This makes them show up in Visual Studio.

### CODE REVIEW

**Review by slime73 — APPROVED** [review]
This looks good to me, I might want to wait until #2036 is merged before merging this though in case doing this first would add merge conflicts for that PR.

**Comment by MikuAuahDark** [comment]
Perhaps it would be possible to auto-generate the `nogame.lua.h` this way too?

**Comment by slime73** [comment]
I'd rather have a separate discussion about that. Personally I wouldn't want to require a lua interpreter just to compile love.

**Comment by slime73** [comment]
This does have merge conflicts now that the other cmake changes are in.

**Comment by learn-more** [comment]
@slime73 I have updated the PR.

**Pull request merged**
